name: s_connectivity
description: A small Flutter utility package to detect Internet connectivity changes and show readyâ€‘toâ€‘use offline UI components
version: 3.0.0
repository: https://github.com/SoundSliced/s_connectivity
issue_tracker: https://github.com/SoundSliced/s_connectivity/issues
homepage: https://github.com/SoundSliced/s_connectivity

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  s_packages: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
